"""MCP tool categories."""

DATA = "DATA"
FACTORS = "FACTORS"
REGIMES = "REGIMES"
RESEARCH = "RESEARCH"
SIMULATION = "SIMULATION"
REPORTS = "REPORTS"
VISUALIZATION = "VISUALIZATION"
SECURITY = "SECURITY"

ALL_CATEGORIES = {
    DATA,
    FACTORS,
    REGIMES,
    RESEARCH,
    SIMULATION,
    REPORTS,
    VISUALIZATION,
    SECURITY,
}

